image: python:3.11  # Utilisé par défaut pour les jobs sauf create-pages

stages:
  - lint
  - security
  - deploy

black:
  image: python:3.11
  stage: lint
  script:
    - pip install black
    - black .
    - git config --global user.name "CI Formatter"
    - git config --global user.email "ci@example.com"  
    - |
      if [ -n "$CI_COMMIT_BRANCH" ]; then
        git checkout -b "$CI_COMMIT_BRANCH"
      else
        echo "CI_COMMIT_BRANCH is empty. Skipping branch creation."
      fi
    - git add .
    - git diff --cached --quiet || git commit -m "Auto-format with Black"
    - git remote set-url origin https://gitlab-ci-token:${COMMIT_TOKEN}@gitlab.com/${CI_PROJECT_PATH}.git
    - git push origin "$CI_COMMIT_BRANCH"

  rules:
    - if: '$CI_COMMIT_BRANCH'
      when: always

pylint:
  image: python:3.11
  stage: lint
  script:
    - pip install pylint
    - pylint masthon/ --fail-under=7.0 --output-format=colorized > pylint.log
  rules:
    - when: always
  allow_failure: true

safety:
  image: python:3.11
  stage: security
  script:
    - pip install safety
    - pip freeze > requirements.txt
    - safety check --file=requirements.txt --full-report --exit-code > safety.log
  rules:
    - when: always
  allow_failure: false

bandit:
  image: python:3.11
  stage: security
  script:
    - pip install bandit
    - bandit -r masthon/ --exclude venv -f json -o bandit-report.json

  rules:
    - if: '$CI_COMMIT_BRANCH != "main"'
    - if: '$CI_COMMIT_BRANCH == "main"'
  allow_failure: false

create-pages:
  image: alpine:latest
  stage: deploy
  pages:
    publish: docs/web_static
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  artifacts:
    paths:
      - docs/web_static
    expire_in: 30 days
  script:
    - echo "nothing to do"
