# The Docker image that will be used to build your app
image: python:3.11  # Utilisé par défaut pour les jobs sauf create-pages

stages:
  - lint
  - security
  - deploy

pylint:
  image: python:3.11
  stage: lint
  script:
    - pip install pylint
    - pylint masthon/ --fail-under=7.0 --output-format=colorized
  rules:
    - when: always  # Lance le job à chaque push, sur toutes les branches
  allow_failure: true

safety:
  image: python:3.11
  stage: security
  script:
    - pip install safety
    - pip freeze > requirements.txt
    - safety check --file=requirements.txt --full-report --exit-code
  rules:
    - if: '$CI_COMMIT_BRANCH != "main"'
    - if: '$CI_COMMIT_BRANCH == "main"'
  allow_failure: false
  
bandit:
  image: python:3.11
  stage: security
  script:
    - pip install bandit
    - bandit -r masthon/ --exclude venv
  rules:
    - if: '$CI_COMMIT_BRANCH != "main"'  # À chaque push sur les branches autres que main
    - if: '$CI_COMMIT_BRANCH == "main"'  # Et aussi sur main après merge
  allow_failure: false



create-pages:
  image: alpine:latest
  stage: deploy
  pages:
    # The folder that contains the files to be exposed at the Page URL
    publish: docs/web_static
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  artifacts:
    paths:
      - docs/web_static
  script:
    - echo "nothing to do"
