[build-system]
requires = ["setuptools"]

[project]
name = "masthon"
version = "v0.1a"
description = "Read the latest Real Python tutorials"
readme = "README.md"
authors = [{ name = "org.literie.gator", email = "aelian.brd@proton.me" }]
license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3"
]
keywords = ["mastodon", "api", "masthon"]
dependencies = [
    "requests",
    "typing",
    "json",
    "traceback"
]
requires-python = ">=3.8"


[project.urls]
Homepage = "https://gitlab.com/Gator3000/masthon"
Bug_Tracker = "https://gitlab.com/Gator3000/masthon/-/issues"