[build-system]
requires = ["setuptools"]

[project]
name = "masthon"
version = "v0.1a"
description = "A simple API for linking masthodon to your python codes."
readme = "README.md"
authors = [{ name = "org.literie.gator", email = "aelian.brd@proton.me" }]
license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Intended Audience :: Developers",
]
keywords = ["mastodon", "api", "masthon"]
dependencies = [
    "requests"
]
requires-python = ">=3.10"


[project.urls]
Homepage = "https://gitlab.com/Gator3000/masthon"
Bug_Tracker = "https://gitlab.com/Gator3000/masthon/-/issues"