"""
2nd example :)

Generate a graph from data collected periodically. (random)
"""

from typing import List

from masthon import DataClasses, Exceptions, Client
from masthon.DataClasses import Visibility


import matplotlib.pyplot as plt
from random import choice
from numpy.random import normal

from time import sleep

plt.style.use("dark_background")

c = Client(token="YOU TOKEN HERE")


# pick a random number in a normal law (from numpy)
def rand():
    d = normal(loc=0, scale=1, size=20)
    return round(float(choice(d)), 3)


# initialize lists
value: float = 0
adders: List[float] = list()
values: List[float] = [value]
colors: List[str] = list()

# all posts to delete them
posts: List[DataClasses.Status] = list()


# looped every 15 seconds
@c.looped_every(15)
def post(client: Client):
    global values, value, posts

    # produce two randow steps in the dataset
    for _ in range(2):
        adders.append(rand())
        colors.append("red" if adders[-1] < 0 else "green")
        value += adders[-1]
        values.append(value)

    # create the graph
    fig = plt.figure()
    axes = fig.add_subplot()
    axes.bar(
        [x + 0.5 for x in range(len(values))][:-1],
        adders,
        bottom=values[:-1],
        color=colors,
        width=0.6,
    )
    axes.plot(values, "wo-")

    fig.savefig("last_graph.jpg")  # save it

    status = client.post_status(
        "My random graph generated by #Matplotlib and published with #Masthon",  # text
        medias=["last_graph.jpg"],  # graph to send
        in_reply_to_id=(
            posts[-1].id if len(posts) > 0 else None
        ),  # the post is replying to last status
        visibility=Visibility.DIRECT,  # prevent from spaming unknown people
    )

    posts.append(status)


@c.add_command(name="clean")
def clean(client: Client):
    """stop program and delete messages"""
    global posts
    for post in reversed(posts):
        try:
            client.delete_status(post)
            sleep(0.5)
        except Exceptions.HTTPRateLimit:
            sleep(30 * 60)
            client.delete_status(post)
    client.stop()  # Artificially stop the loop


c.run()
