# All custom exceptions are childrens of this class
class MasthonException(BaseException):...

# Class of CLI exceptions
class CLIException(MasthonException):...

class CommandNotFound(CLIException):...

class CommandExecutionError(CLIException, RuntimeError):...